import { VerticalBox, HorizontalBox, Button } from "std-widgets.slint";
export{ LoginWindow } from "./login.slint";

export component AppWindow inherits Window {
    callback handle-logout();
    width: 960px;
    height: 540px;
    title: "MES";
    Rectangle {
        width: parent.width;
        height: parent.height;
        background: #f5f5f5;
        VerticalBox {
            width: parent.width;
            height: parent.height;
            
            Rectangle {
                width: parent.width;
                height: 60px;
                background: #4361ee;
                HorizontalBox {
                    alignment: center;
                    spacing: 10px;
                    padding: 10px;
                    Text {
                        text: "制造执行系统";
                        color: white;
                        font-size: 20px;
                        font-weight: 700;
                    }

                    Button {
                        text: "退出登录";
                        clicked => {
                            root.handle-logout();
                        }
                    }
                }
            }
            
            Rectangle {
                width: parent.width;
                height: parent.height - 60px;
                background: white;
                VerticalBox {
                    alignment: center;
                    padding: 40px;
                    
                    Text {
                        text: "主界面内容...";
                        color: #6c757d;
                        font-size: 16px;
                    }
                }
            }
        }
    }
}
