import {
    TabWidget,
    HorizontalBox,
} from "std-widgets.slint";
import { VerticalDivider } from "components/divider.slint";
import { State } from "state.slint";
import { Task } from "task.slint";
import { Recipe } from "recipe.slint";
import { Acctount } from "account.slint";

export{ LoginWindow } from "./login_window.slint";

export { RecipeInteraction } from "./recipe.slint";
export { AccountInteraction } from "./account.slint";

export component AppWindow inherits Window {
    callback handle-logout();
    min-width: 1024px;
    min-height: 540px;
    title: "MES";
    TabWidget {
        Tab {
            title: "状态";
            State { }
        }

        Tab {
            title: "任务";
            Task { }
        }

        Tab {
            title: "配方";
            Recipe { }
        }

        Tab {
            title: "步骤";
        }

        Tab {
            title: "计划";
        }

        Tab {
            title: "账户";
            Acctount { }
        }
    }
}
