local Label = require("ui.label")
local Panel = require("ui.panel")
local Button = require("ui.button")
local Input = require("ui.input")
local CheckBox = require("ui.checkbox")
local ProgressBar = require("ui.progressbar")
local List = require("ui.list")

require("src.recipe_ui")

---@return Widget
function MainUI()
    local ec_panel = Panel.new(1, 1, 80, 25, "EC")

    local power_button = Button.new(75, 2, 5, 3, function()
    end, "", 0xFFFFFF, 0xFF0000, 0x00FF00)
    local state_button = Button.new(60, 2, 15, 3, function()
    end, "OnlineRemote", 0xFFFFFF, 0x00FF00)
    local recipe_button = Button.new(2, 2, 15, 3, function()
        ec_panel:disable_child_event()
        local recipe_panel = Recipe(ec_panel)
        ec_panel:add_child(recipe_panel)
    end, "Recipe")
    local exec_button = Button.new(33, 2, 15, 3, function()
    end, "Exec")

    local status_panel = Panel.new(41, 5, 40, 21, "state")
    local chamber_panel = Panel.new(1, 5, 40, 21, "chamber")

    ec_panel:add_child(power_button)
    ec_panel:add_child(state_button)
    ec_panel:add_child(recipe_button)
    ec_panel:add_child(exec_button)
    ec_panel:add_child(status_panel)
    ec_panel:add_child(chamber_panel)

    local chamber1_button = Button.new(11, 14, 10, 5, function()
    end, "C1")
    local chamber2_button = Button.new(21, 14, 10, 5, function()
    end, "C2")
    local chamber3_button = Button.new(11, 9, 10, 5, function()
    end, "C3")
    local chamber4_button = Button.new(21, 9, 10, 5, function()
    end, "C4")
    local chamber5_button = Button.new(11, 4, 10, 5, function()
    end, "C5")
    local chamber6_button = Button.new(21, 4, 10, 5, function()
    end, "C6")
    chamber_panel:add_child(chamber1_button)
    chamber_panel:add_child(chamber2_button)
    chamber_panel:add_child(chamber3_button)
    chamber_panel:add_child(chamber4_button)
    chamber_panel:add_child(chamber5_button)
    chamber_panel:add_child(chamber6_button)
    return ec_panel
end
